version: '3.8'

services:

    # Laravel app
    mtmkay_app:
        build:
            args:
                user: mtmkay_user
                uid: 1000
            context: .
            dockerfile: Dockerfile
        platform: linux/amd64
        image: mtmkay_app_image
        container_name: mtmkay_app_container
        restart: unless-stopped
        working_dir: /var/www
        depends_on:
            - mtmkay_mysql
        volumes:
            - ./:/var/www
        networks:
            - mtmkay_network

    # Nginx Service
    mtmkay_nginx:
        platform: linux/amd64
        image: nginx:alpine
        container_name: mtmkay_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        depends_on:
            - mtmkay_app
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx/:/etc/nginx/conf.d
        networks:
            - mtmkay_network

    # MySQL Service
    mtmkay_mysql:
        platform: linux/amd64
        image: mysql:latest
        container_name: mtmkay_mysql_container
        restart: unless-stopped
        ports:
            - "3337:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_USER_PASSWORD}
        networks:
            - mtmkay_network
        volumes:
            -   mtmkay_mysql_data:/var/lib/mysql
            -   ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf

#     phpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin:5.2.1-apache
        container_name: mtmkay_phpmyadmin
        restart: unless-stopped
        ports:
            - "8383:80"
        environment:
            - PMA_HOST=mtmkay_mysql
            - PMA_PORT=3306
            - PMA_USER=${DB_USER}
            - PMA_PASSWORD=${DB_USER_PASSWORD}
        depends_on:
            - mtmkay_mysql
        networks:
            - mtmkay_network

networks:
    mtmkay_network:
        driver: bridge
volumes:
    mtmkay_mysql_data:
        driver: local
